#Compilers
PCC = mpicc
#PCC = tau_cc.sh
FORTRAN = gfortran

#Flags for debugging
FLAGS = -std=gnu99
#FLAGS = -g -std=gnu99
#FLAGS = -g -std=c99 -Wunused-parameter -Wall -Wextra #-Wpadded
#FLAGS = -g -std=c99 -pg -L/home/scott/fpmpi-2.1g

#Flags for performance
OPTFLAGS = -O3 -march=nocona

#Flags for printing data
#PRINTFLAG = -D PRINTPEAKFLOW #-D MONTHLYEVAP -D PRINT2DATABASE

#TAU Stuff
#CFLAGS = $(TAU_INCLUDE) $(TAU_DEFS) $(TAU_MPI_INCLUDE)
#TAULIBS = $(TAU_MPI_LIBS) $(TAU_LIBS) -lm
#LDFLAGS = $(USER_OPT) $(TAU_LDFLAGS)
#ALLTAUFLAGS = $(CFLAGS) $(TAULIBS) $(LDFLAGS) -tau_makefile=~/tau-2.21.4/x86_64/lib/Makefile.tau-mpi -optCompInst

#Header and library locations
HEADLOC = -I/Users/ssma/metis/include/
LIBSLOC = -L/Users/ssma/metis/lib/

#Libraries
#LIBS = -lm -lpq -L/usr/lib64/atlas/
#LIBS = -lm -lpq -L/usr/lib64/atlas/ -llapack -lf77blas -lcblas -latlas
#LIBS = -lm -lpq
LIBS = $(LIBSLOC) -lm -lpq -lmetis

#Objects
SHAREDOBJS = rkmethods.o problems.o mathmethods.o riversys.o sort.o comm.o system.o processdata.o partition.o definetype.o misc.o \
	rainfall.o solvers.o io.o forcings.o compression.o date_manip.o asynch_interface.o modeloutputs.o data_types.o
FORECASTEROBJS = forecaster_methods.o
ASYNCHDISTOBJS = asynchdist.o
ASYNCHPERSISOBJS = asynchpersis.o
FORECASTER_MAPS = forecaster_maps.o
PEANOOBJS = buildpeano.o
SIMPLEOBJS = simplemethods.o simple.o
FSIMPLEOBJS = dopri5.o solout.o
DIRACOBJS = dirac.o
ASYNCHPERSISTESTOBJS = asynchpersistest.o
ASYNCHPERSISFELIPEOBJS = asynchpersisFelipe.o
ASYNCHPERSISBONGCHULOBJS = asynchpersisBongChul.o
SNOWMELTOBJS = asynchpersissnow.o
EQUIVOBJS = asynchpersisequiv.o
MAPSSTOPOBJS = forecaster_maps_stop.o
OUTLOOKOBJS = asynch_outlook2014.o
ASSIMSCALEOBJS = assim_scale.o

#Locations
OBJDIR = ./objects
FOBJDIR = ./objects
SHAREDOBJSLOC = $(addprefix $(OBJDIR)/,$(SHAREDOBJS))
FORECASTEROBJSLOC = $(addprefix $(OBJDIR)/,$(FORECASTEROBJS))
ASYNCHDISTOBJSLOC = $(addprefix $(OBJDIR)/,$(ASYNCHDISTOBJS))
ASYNCHPERSISOBJSLOC = $(addprefix $(OBJDIR)/,$(ASYNCHPERSISOBJS))
FORECASTER_MAPSOBJSLOC = $(addprefix $(OBJDIR)/,$(FORECASTER_MAPS))
PEANOOBJSLOC = $(addprefix $(OBJDIR)/,$(PEANOOBJS))
SIMPLEOBJSLOC = $(addprefix $(OBJDIR)/,$(SIMPLEOBJS))
FSIMPLEOBJSLOC = $(addprefix $(FOBJDIR)/,$(FSIMPLEOBJS))
DIRACOBJSLOC = $(addprefix $(OBJDIR)/,$(DIRACOBJS))
ASYNCHPERSISTESTOBJSLOC = $(addprefix $(OBJDIR)/,$(ASYNCHPERSISTESTOBJS))
ASYNCHPERSISFELIPEOBJSLOC = $(addprefix $(OBJDIR)/,$(ASYNCHPERSISFELIPEOBJS))
ASYNCHPERSISBONGCHULOBJSLOC = $(addprefix $(OBJDIR)/,$(ASYNCHPERSISBONGCHULOBJS))
SNOWMELTOBJSLOC = $(addprefix $(OBJDIR)/,$(SNOWMELTOBJS))
EQUIVOBJSLOC = $(addprefix $(OBJDIR)/,$(EQUIVOBJS))
MAPSSTOPOBJSLOC = $(addprefix $(OBJDIR)/,$(MAPSSTOPOBJS))
OUTLOOKOBJSLOC = $(addprefix $(OBJDIR)/,$(OUTLOOKOBJS))
ASSIMSCALEOBJSLOC = $(addprefix $(OBJDIR)/,$(ASSIMSCALEOBJS))

#How to compile and link
$(OBJDIR)/%.o: %.c
	$(PCC) -c $*.c $(HEADLOC) $(FLAGS) $(OPTFLAGS) $(ALLTAUFLAGS) $(PRINTFLAG) -o $(OBJDIR)/$*.o $(STORE)

$(FOBJDIR)/%.o: %.f
	$(FORTRAN) -c $*.f $(HEADLOC) $(FLAGS) $(OPTFLAGS) $(PRINTFLAG) -o $(FOBJDIR)/$*.o

ASYNCH: $(SHAREDOBJSLOC) $(ASYNCHDISTOBJSLOC)
	$(PCC) $(SHAREDOBJSLOC) $(ASYNCHDISTOBJSLOC) $(LIBS) $(FLAGS) $(OPTFLAGS) $(ALLTAUFLAGS) $(PRINTFLAG) -o ASYNCH

ASYNCHPERSIS: $(SHAREDOBJSLOC) $(FORECASTEROBJSLOC) $(ASYNCHPERSISOBJSLOC)
	$(PCC) $(SHAREDOBJSLOC) $(FORECASTEROBJSLOC) $(ASYNCHPERSISOBJSLOC) $(LIBS) $(FLAGS) $(OPTFLAGS) $(PRINTFLAG) -o ASYNCHPERSIS

FORECASTER_MAPS: $(SHAREDOBJSLOC) $(FORECASTEROBJSLOC) $(FORECASTER_MAPSOBJSLOC)
	$(PCC) $(SHAREDOBJSLOC) $(FORECASTEROBJSLOC) $(FORECASTER_MAPSOBJSLOC) $(LIBS) $(FLAGS) $(OPTFLAGS) $(PRINTFLAG) -o FORECASTER_MAPS

PEANO: $(PEANOOBJSLOC)
	$(PCC) $(PEANOOBJSLOC) $(LIBS) $(FLAGS) $(OPTFLAGS) -o PEANO

SIMPLE: $(SIMPLEOBJSLOC) $(FSIMPLEOBJSLOC) $(SHAREDOBJSLOC)
	$(FORTRAN) $(SIMPLEOBJSLOC) $(FSIMPLEOBJSLOC) $(SHAREDOBJSLOC) $(LIBS) $(FLAGS) $(OPTFLAGS) -o SIMPLE \
		-I/opt/openmpi/1.4.3/gnu/include -pthread -L/opt/openmpi/1.4.3/gnu/lib -lmpi -lopen-rte -lopen-pal -ldl -Wl,--export-dynamic -lnsl -lutil -lm -ldl

DIRAC: $(SHAREDOBJSLOC) $(DIRACOBJSLOC)
	$(PCC) $(SHAREDOBJSLOC) $(DIRACOBJSLOC) $(LIBS) $(FLAGS) $(OPTFLAGS) $(PRINTFLAG) -o DIRAC

ASYNCHPERSISTEST: $(SHAREDOBJSLOC) $(ASYNCHPERSISTESTOBJSLOC)
	$(PCC) $(SHAREDOBJSLOC) $(ASYNCHPERSISTESTOBJSLOC) $(LIBS) $(FLAGS) $(OPTFLAGS) $(PRINTFLAG) -o ASYNCHPERSISTEST

ASYNCHPERSISFELIPE: $(SHAREDOBJSLOC) $(ASYNCHPERSISFELIPEOBJSLOC)
	$(PCC) $(SHAREDOBJSLOC) $(ASYNCHPERSISFELIPEOBJSLOC) $(LIBS) $(FLAGS) $(OPTFLAGS) $(PRINTFLAG) -o ASYNCHPERSISFELIPE

ASYNCHPERSISBONGCHUL: $(SHAREDOBJSLOC) $(ASYNCHPERSISBONGCHULOBJSLOC)
	$(PCC) $(SHAREDOBJSLOC) $(ASYNCHPERSISBONGCHULOBJSLOC) $(LIBS) $(FLAGS) $(OPTFLAGS) $(PRINTFLAG) -o ASYNCHPERSISBONGCHUL

SNOWMELT: $(SHAREDOBJSLOC) $(SNOWMELTOBJSLOC)
	$(PCC) $(SHAREDOBJSLOC) $(SNOWMELTOBJSLOC) $(LIBS) $(FLAGS) $(OPTFLAGS) $(PRINTFLAG) -o SNOWMELT

EQUIV: $(SHAREDOBJSLOC) $(EQUIVOBJSLOC)
	$(PCC) $(SHAREDOBJSLOC) $(EQUIVOBJSLOC) $(LIBS) $(FLAGS) $(OPTFLAGS) $(PRINTFLAG) -o EQUIV

MAPS_STOP: $(SHAREDOBJSLOC) $(MAPSSTOPOBJSLOC)
	$(PCC) $(SHAREDOBJSLOC) $(MAPSSTOPOBJSLOC) $(LIBS) $(FLAGS) $(OPTFLAGS) $(PRINTFLAG) -o MAPS_STOP

OUTLOOK: $(SHAREDOBJSLOC) $(OUTLOOKOBJSLOC)
	$(PCC) $(SHAREDOBJSLOC) $(OUTLOOKOBJSLOC) $(LIBS) $(FLAGS) $(OPTFLAGS) $(ALLTAUFLAGS) $(PRINTFLAG) -o OUTLOOK

ASSIMSCALE: $(SHAREDOBJSLOC) $(FORECASTEROBJSLOC) $(ASSIMSCALEOBJSLOC)
	$(PCC) $(SHAREDOBJSLOC) $(FORECASTEROBJSLOC) $(ASSIMSCALEOBJSLOC) $(LIBS) $(FLAGS) $(OPTFLAGS) $(PRINTFLAG) -o ASSIMSCALE

clean:
	rm -f $(OBJDIR)/*.o
	rm -f ASYNCH
	rm -f ASYNCHPERSIS
	rm -f FORECASTER_MAPS
	rm -f PEANO
	rm -f SIMPLE
	rm -f DIRAC
	rm -f ASYNCHPERSISTEST
	rm -f ASYNCHPERSISFELIPE
	rm -f ASYNCHPERSISBONGCHUL
	rm -f SNOWMELT
	rm -f EQUIV
	rm -f MAPS_STOP

